version: '2'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 127.0.0.1:27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 127.0.0.1:3002:8081
